// Generado a partir de BackEnd/bbdd.xml — metadatos de UI del formulario de Carrozado.
export type BodyworkFieldType = "text" | "int" | "float" | "bool";

export const BODYWORK_SECTIONS = {
  general: "General",
  dimensiones: "Dimensiones",
  piso: "Piso",
  techo: "Techo",
  laterales: "Laterales",
  zocalo: "Zócalo",
  subchasis: "Subchasis",
  base: "Base y recerco",
  amarres: "Amarres",
  cortavientos: "Cortavientos",
  plataforma: "Plataforma elevadora",
  puertas: "Puertas",
  accesorios: "Accesorios",
  otros: "Acoplamiento y varios",
} as const;

export type BodyworkSection = keyof typeof BODYWORK_SECTIONS;

export const BODYWORK_FIELDS: { name: string; label: string; type: BodyworkFieldType; section: BodyworkSection }[] = [
  { name: "bodyType", label: "Tipo carrozado", type: "text", section: "general" },
  { name: "exteriorLength", label: "Largo exterior", type: "float", section: "dimensiones" },
  { name: "interiorLength", label: "Largo interior", type: "float", section: "dimensiones" },
  { name: "exteriorWidth", label: "Ancho exterior", type: "float", section: "dimensiones" },
  { name: "interiorWidth", label: "Ancho interior", type: "float", section: "dimensiones" },
  { name: "interiorHeight", label: "Alto interior", type: "float", section: "dimensiones" },
  { name: "sidePitch", label: "Paso lateral", type: "float", section: "dimensiones" },
  { name: "floorType", label: "Tipo de piso", type: "text", section: "piso" },
  { name: "floorThickness", label: "Espesor piso", type: "float", section: "piso" },
  { name: "floorWeightPerM2", label: "Peso piso", type: "float", section: "piso" },
  { name: "sideColor", label: "Color laterales", type: "text", section: "laterales" },
  { name: "roofMaterial", label: "Material techo", type: "text", section: "techo" },
  { name: "roofMaterialWeightPerM2", label: "Peso material techo", type: "float", section: "techo" },
  { name: "sideMaterial", label: "Material lateral", type: "text", section: "laterales" },
  { name: "sideMaterialWeightPerM2", label: "Peso M2 material lateral", type: "float", section: "laterales" },
  { name: "sideStructureMaterial", label: "Material estrucctura lateral", type: "int", section: "laterales" },
  { name: "sideStructureTubeWeightPerMeter", label: "Peso Mlineal tubo estructura laterales", type: "float", section: "laterales" },
  { name: "skirtSheet", label: "Zocalo chapa", type: "text", section: "zocalo" },
  { name: "skirtWeightPerM2", label: "Pesom2 zocalo", type: "float", section: "zocalo" },
  { name: "subchassisProfile", label: "Perfil subchasis", type: "text", section: "subchasis" },
  { name: "subchassisMaterialWeightPerMeter", label: "Peso Mlineal material subchasis", type: "float", section: "subchasis" },
  { name: "windDeflector", label: "Cortavientos", type: "text", section: "cortavientos" },
  { name: "windDeflectorHeight", label: "Alto cortavientos", type: "float", section: "cortavientos" },
  { name: "windDeflectorWeight", label: "Peso cortavientos", type: "float", section: "cortavientos" },
  { name: "liftPlatformType", label: "Tipo Plataforma elevadora", type: "text", section: "plataforma" },
  { name: "liftPlatformCapacity", label: "Capacidad plataforma elevadora", type: "float", section: "plataforma" },
  { name: "liftPlatformVoltage", label: "Tension plataforma elevadora", type: "float", section: "plataforma" },
  { name: "liftPlatformBrand", label: "Marca plataforma elevadora", type: "text", section: "plataforma" },
  { name: "liftPlatformWeight", label: "Peso plataformalevadora", type: "float", section: "plataforma" },
  { name: "liftPlatformFitted", label: "Plataforma elevadora", type: "text", section: "plataforma" },
  { name: "roofStructureMaterial", label: "Material estructura techo", type: "int", section: "techo" },
  { name: "roofStructureMaterialWeightPerMeter", label: "Peso material Estructura techo", type: "float", section: "techo" },
  { name: "trimMaterial", label: "Material de recerco", type: "text", section: "base" },
  { name: "trimWeightPerMeter", label: "Peso metro lineal recerco", type: "float", section: "base" },
  { name: "tieDownMaterial", label: "Material amarre interior", type: "text", section: "amarres" },
  { name: "tieDownCount", label: "Numero de amarres", type: "int", section: "amarres" },
  { name: "tieDownWeightPerMeter", label: "Peso metrolineal amarre", type: "float", section: "amarres" },
  { name: "baseMaterial", label: "Material base", type: "int", section: "base" },
  { name: "baseMaterialWeightPerMeter", label: "Peso metro lineal material base", type: "float", section: "base" },
  { name: "doorLined", label: "Forrado interior puertas", type: "bool", section: "puertas" },
  { name: "doorLatchCount", label: "Numero fallebas puertas", type: "int", section: "puertas" },
  { name: "hingesPerDoor", label: "Numero bisagras por puerta", type: "int", section: "puertas" },
  { name: "hardwareMaterial", label: "Material herrajes", type: "text", section: "puertas" },
  { name: "doorType", label: "Puerta porton", type: "text", section: "puertas" },
  { name: "doorFiberWeightPerM2", label: "Peso M2 fibra puertas", type: "float", section: "puertas" },
  { name: "doorLatchUnitWeight", label: "Peso falleba unidad", type: "float", section: "puertas" },
  { name: "hingeUnitWeight", label: "Peso bisagra unidad", type: "float", section: "puertas" },
  { name: "otherAccessories", label: "Otros Accesorios", type: "text", section: "accesorios" },
  { name: "otherAccessoriesWeight", label: "Peso otros accesorios", type: "float", section: "accesorios" },
  { name: "toolBox", label: "Cajon herramientas", type: "text", section: "accesorios" },
  { name: "extinguisherBox", label: "Cajon extintor", type: "text", section: "accesorios" },
  { name: "toolBoxWeight", label: "Peso Cajon herramientas", type: "float", section: "accesorios" },
  { name: "extinguisherBoxWeight", label: "Peso cajon extintor", type: "float", section: "accesorios" },
  { name: "toolBoxSize", label: "Tam cajon herramientas", type: "text", section: "accesorios" },
  { name: "couplingDevice", label: "Dispositivo acoplamiento", type: "text", section: "otros" },
  { name: "couplingDeviceBrand", label: "Marca disp acoplamiento", type: "text", section: "otros" },
  { name: "couplingDeviceSerialNumber", label: "Nserie disp acoplamiento", type: "text", section: "otros" },
  { name: "rearProtectionBrand", label: "Marca prot trasera", type: "text", section: "otros" },
  { name: "rearProtection", label: "Prot trasera", type: "text", section: "otros" },
  { name: "rearProtectionModel", label: "Modelo prot trasera", type: "text", section: "otros" },
  { name: "rearProtectionApprovalNumber", label: "Contraseña prot trasera", type: "text", section: "otros" },
  { name: "otherElectricalEquipment", label: "Otros equipos electricos electronicos", type: "text", section: "otros" },
  { name: "leafSpringReinforcement", label: "Refuerzoballesta", type: "text", section: "otros" },
  { name: "leafSpringReinforcementWeight", label: "Peso refuerzo ballesta", type: "float", section: "otros" },
  { name: "interiorLight", label: "Luzinterior", type: "text", section: "otros" },
];
