// Generado a partir de BackEnd/bbdd.xml — metadatos de UI para el formulario de COC.
// No confundir con el esquema de Prisma: esto es solo label+tipo+sección para renderizar.
export type CocFieldType = "text" | "int" | "float" | "date";

export const COC_SECTIONS = {
  identificacion: "Identificación del vehículo",
  constitucion: "Constitución general",
  dimensiones: "Dimensiones principales",
  masas: "Masas",
  motor: "Unidad motriz",
  ejes: "Ejes y neumáticos",
  frenos: "Frenos",
  acoplamiento: "Dispositivo de acoplamiento",
  medioambiental: "Eficiencia medioambiental",
  varios: "Varios",
  ficha_reducida: "Ficha reducida",
} as const;

export type CocSection = keyof typeof COC_SECTIONS;

export const COC_FIELDS: { name: string; label: string; type: CocFieldType; section: CocSection; clause: string }[] = [
  { name: "vin", label: "VIN", type: "text", section: "identificacion", clause: "0.10" },
  { name: "vehicleCategory", label: "Categoria vehiculo", type: "text", section: "identificacion", clause: "0.4" },
  { name: "brand", label: "Marca", type: "text", section: "identificacion", clause: "0.1" },
  { name: "type", label: "Tipo", type: "text", section: "identificacion", clause: "0.2" },
  { name: "variant", label: "Variante", type: "text", section: "identificacion", clause: "0.2" },
  { name: "version", label: "Version", type: "text", section: "identificacion", clause: "0.2" },
  { name: "commercialName", label: "Nombre comercial", type: "text", section: "identificacion", clause: "0.2.1" },
  { name: "manufacturerName", label: "Nombre fabricante", type: "text", section: "identificacion", clause: "0.5" },
  { name: "manufacturerAddress", label: "Dirección fabricante", type: "text", section: "identificacion", clause: "0.5" },
  { name: "vinLocation", label: "Ubicacion VIN", type: "text", section: "identificacion", clause: "0.6" },
  { name: "platesAttachmentMethod", label: "Colocacion placas reglamentarias", type: "text", section: "identificacion", clause: "0.6" },
  { name: "platesLocation", label: "Ubicacion placas reglamentarias", type: "text", section: "identificacion", clause: "0.6" },
  { name: "approvalDate", label: "Fecha homologacion", type: "date", section: "identificacion", clause: "0.11" },
  { name: "manufactureDate", label: "Fecha fabricación", type: "date", section: "identificacion", clause: "0.11" },
  { name: "approvalNumber", label: "Contraseña homologacion", type: "text", section: "identificacion", clause: "0.11" },
  { name: "wheelCount", label: "Numero ruedas", type: "int", section: "constitucion", clause: "1" },
  { name: "axleCount", label: "Numero ejes", type: "int", section: "constitucion", clause: "1" },
  { name: "dualWheelAxlePosition", label: "Posicion ejes doble rueda", type: "int", section: "constitucion", clause: "1.1" },
  { name: "dualWheelAxleCount", label: "Numero ejes doble rueda", type: "int", section: "constitucion", clause: "1.1" },
  { name: "steeredAxlePosition", label: "Posicion ejes direcionables", type: "int", section: "constitucion", clause: "2" },
  { name: "steeredAxleCount", label: "Numero ejes direcionables", type: "int", section: "constitucion", clause: "2" },
  { name: "drivenAxleCount", label: "Numero ejes motores", type: "int", section: "constitucion", clause: "3" },
  { name: "drivenAxleLocation", label: "Localizacion ejes motores", type: "int", section: "constitucion", clause: "3" },
  { name: "drivenAxleInterconnection", label: "Interconexion ejes motores", type: "text", section: "constitucion", clause: "3" },
  { name: "axleDistance0to1", label: "Distancia entre ejes 0 1", type: "float", section: "dimensiones", clause: "4.1" },
  { name: "axleDistance1to2", label: "Distancia entre ejes 1y2", type: "float", section: "dimensiones", clause: "4.1" },
  { name: "axleDistance2to3", label: "Distancia entre ejes 2y3", type: "float", section: "dimensiones", clause: "4.1" },
  { name: "maxPermissibleLength", label: "Maximo largo permisible", type: "float", section: "dimensiones", clause: "5.1" },
  { name: "maxPermissibleWidth", label: "Maximo ancho permisible", type: "float", section: "dimensiones", clause: "6.1" },
  { name: "maxPermissibleHeight", label: "Altura max admisible", type: "float", section: "dimensiones", clause: "7.1" },
  { name: "pivotToRearEdgeDistance", label: "Distancia pivote borde trasero vehículo", type: "float", section: "dimensiones", clause: "10" },
  { name: "kingpinToRearEdgeDistance", label: "Distancia kingpin a borde trasero vehículo", type: "float", section: "dimensiones", clause: "10.1" },
  { name: "maxPermissibleRearOverhang", label: "Maximo voladizo trasero permisible", type: "float", section: "dimensiones", clause: "12.1" },
  { name: "momIncompleteVehicle", label: "MOM vehiculo incompleto", type: "float", section: "masas", clause: "14" },
  { name: "momIncompleteAxle3", label: "MOM incompleto eje 3", type: "float", section: "masas", clause: "14.1" },
  { name: "momIncompleteAxle2", label: "MOM incompleto eje 2", type: "float", section: "masas", clause: "14.1" },
  { name: "momIncompleteAxle1", label: "MOM incompleto eje 1", type: "float", section: "masas", clause: "14.1" },
  { name: "currentIncompleteVehicleMass", label: "Masa Actual vehiculo incompleto", type: "float", section: "masas", clause: "14.2" },
  { name: "minCompletedMass", label: "Masa minima completado", type: "float", section: "masas", clause: "15" },
  { name: "minCompletedMassDistributionAxle1", label: "Reparto m minima completado eje 1", type: "float", section: "masas", clause: "15.1" },
  { name: "minCompletedMassDistributionAxle2", label: "Reparto m minima completado eje 2", type: "float", section: "masas", clause: "15.1" },
  { name: "minCompletedMassDistributionAxle3", label: "Reparto m minima completado eje 3", type: "float", section: "masas", clause: "15.1" },
  { name: "maxTechnicallyPermissibleMass", label: "Masa maxima tecnicamente Admisible", type: "float", section: "masas", clause: "16.1" },
  { name: "maxTechnicallyPermissibleMassRequested", label: "Masa máxima técnicamente admisible solicitada", type: "float", section: "masas", clause: "16.1.1" },
  { name: "maxTechnicallyPermissibleMassAxleGroup2", label: "Masa maxima tecnicamente Admisible grupo ejes2", type: "float", section: "masas", clause: "16.3" },
  { name: "maxTechnicallyPermissibleMassAxleGroup1", label: "Masa maxima tecnicamente Admisible grupo ejes1", type: "float", section: "masas", clause: "16.3" },
  { name: "maxTechnicallyPermissibleMassAxle3", label: "Masa maxima tecnicamente Admisible eje 3", type: "float", section: "masas", clause: "16.2" },
  { name: "maxTechnicallyPermissibleMassAxle2", label: "Masa maxima tecnicamente Admisible eje 2", type: "float", section: "masas", clause: "16.2" },
  { name: "maxTechnicallyPermissibleMassAxle1", label: "Masa maxima tecnicamente Admisible eje 1", type: "float", section: "masas", clause: "16.2" },
  { name: "maxTechnicallyPermissibleMassCombination", label: "Masa maxima tecnicamente Admisible conjunto", type: "float", section: "masas", clause: "16.4" },
  { name: "maxLadenMassRegistration", label: "Masa maxima encarga Admisible matriculacion", type: "float", section: "masas", clause: "17.1" },
  { name: "maxLadenMassRegistrationAxle3", label: "Masa maxima encarga Admisible matriculacion eje 3", type: "float", section: "masas", clause: "17.2" },
  { name: "maxLadenMassRegistrationAxle2", label: "Masa maxima encarga Admisible matriculacion eje 2", type: "float", section: "masas", clause: "17.2" },
  { name: "maxLadenMassRegistrationAxle1", label: "Masa maxima encarga Admisible matriculacion eje 1", type: "float", section: "masas", clause: "17.2" },
  { name: "maxLadenMassRegistrationAxleGroup1", label: "Masa max admisible matriculacion grupo1", type: "float", section: "masas", clause: "17.3" },
  { name: "maxLadenMassRegistrationCombination", label: "Masa maxima admisible conjunto matriculacion", type: "float", section: "masas", clause: "17.4" },
  { name: "semiTrailerMass", label: "Masa semiremolque", type: "float", section: "masas", clause: "18.2" },
  { name: "drawBarTrailerMass", label: "Masa remolque barra tracion", type: "float", section: "masas", clause: "18.1" },
  { name: "centreAxleTrailerMass", label: "Masa remolque eje central", type: "float", section: "masas", clause: "18.3" },
  { name: "rigidDrawBarTrailerMass", label: "Masa remolque barra rigida", type: "float", section: "masas", clause: "18.3.1" },
  { name: "unbrakedTrailerMass", label: "Masa remolque sin frenos", type: "float", section: "masas", clause: "18.4" },
  { name: "staticCouplingPointMass", label: "Masa estatica punto acoplamiento", type: "float", section: "masas", clause: "19" },
  { name: "staticKingpinMass", label: "1 Masa estatica Kingpin", type: "float", section: "masas", clause: "19.1" },
  { name: "engineManufacturer", label: "Fabricante motor", type: "text", section: "motor", clause: "20" },
  { name: "engineMarkingCode", label: "Codigo marcado motor", type: "text", section: "motor", clause: "21" },
  { name: "operatingPrinciple", label: "Principio funcionamiento", type: "text", section: "motor", clause: "22" },
  { name: "pureElectric", label: "Electrico puro", type: "text", section: "motor", clause: "23" },
  { name: "hybrid", label: "Hibrido", type: "text", section: "motor", clause: "23.1" },
  { name: "cylinderCount", label: "Numero cilindros", type: "int", section: "motor", clause: "24" },
  { name: "cylinderArrangement", label: "Disposicion cilindros", type: "text", section: "motor", clause: "24.1" },
  { name: "displacement", label: "Cilindrada", type: "float", section: "motor", clause: "25" },
  { name: "fuelType", label: "Combustible", type: "int", section: "motor", clause: "26" },
  { name: "singleFuel", label: "Monocombustible", type: "text", section: "motor", clause: "26.1" },
  { name: "ratedPower", label: "Potencia nominal", type: "float", section: "motor", clause: "27.1" },
  { name: "ratedPowerRpm", label: "RPM Potencia nominal", type: "float", section: "motor", clause: "27.1" },
  { name: "maxNetPower", label: "Potencia maxima neta", type: "float", section: "motor", clause: "27.3" },
  { name: "gearboxType", label: "Caja cambios tipo", type: "text", section: "motor", clause: "28" },
  { name: "maxSpeed", label: "Velocidad maxima", type: "float", section: "motor", clause: "29" },
  { name: "trackWidthAxle1", label: "Ancho via eje 1", type: "float", section: "ejes", clause: "30" },
  { name: "trackWidthAxle2", label: "Ancho via eje 2", type: "float", section: "ejes", clause: "30.1" },
  { name: "trackWidthAxle3", label: "Ancho via eje 3", type: "float", section: "ejes", clause: "30.2" },
  { name: "retractableAxlePosition", label: "Posicion ejes retractiles", type: "int", section: "ejes", clause: "31" },
  { name: "liftableAxlePosition", label: "Posicion ejes cargables", type: "int", section: "ejes", clause: "32" },
  { name: "pneumaticSteeredAxles", label: "Ejes directores neumaticos", type: "text", section: "ejes", clause: "33" },
  { name: "tireCount", label: "Numero neumaticos", type: "int", section: "ejes", clause: "35" },
  { name: "tireWidthAxle1", label: "Ancho neumatico eje 1", type: "float", section: "ejes", clause: "35" },
  { name: "tireWidthAxle2", label: "Ancho neumatico eje 2", type: "float", section: "ejes", clause: "35" },
  { name: "tireWidthAxle3", label: "Ancho neumatico eje 3", type: "float", section: "ejes", clause: "35" },
  { name: "tireAspectRatioAxle1", label: "Alto neumatico eje 1", type: "float", section: "ejes", clause: "35" },
  { name: "tireAspectRatioAxle2", label: "Alto neumatico eje 2", type: "float", section: "ejes", clause: "35" },
  { name: "tireAspectRatioAxle3", label: "Alto neumatico eje 3", type: "float", section: "ejes", clause: "35" },
  { name: "rimDiameterAxle1", label: "LLanta neumatico eje 1", type: "float", section: "ejes", clause: "35" },
  { name: "rimDiameterAxle2", label: "LLanta neumatico eje 2", type: "float", section: "ejes", clause: "35" },
  { name: "rimDiameterAxle3", label: "LLanta neumatico eje 3", type: "float", section: "ejes", clause: "35" },
  { name: "speedRatingAxle1", label: "Indice velocidad eje 1", type: "text", section: "ejes", clause: "35" },
  { name: "speedRatingAxle2", label: "Indice velocidad eje 2", type: "text", section: "ejes", clause: "35" },
  { name: "speedRatingAxle3", label: "Indice velocidad eje 3", type: "text", section: "ejes", clause: "35" },
  { name: "loadIndexAxle1", label: "Indice carga eje 1", type: "int", section: "ejes", clause: "35" },
  { name: "loadIndexAxle2", label: "Indice carga eje 2", type: "int", section: "ejes", clause: "35" },
  { name: "loadIndexAxle3", label: "Indice carga eje 3", type: "int", section: "ejes", clause: "35" },
  { name: "trailerBrakeConnectionType", label: "Tipo de conexión freno de remolque", type: "text", section: "frenos", clause: "36" },
  { name: "brakingPressure", label: "Presion frenado", type: "float", section: "frenos", clause: "37" },
  { name: "couplingDeviceApprovalNumber", label: "Nhomologacion dispositivo acoplamiento", type: "text", section: "acoplamiento", clause: "44" },
  { name: "couplingDeviceBrand", label: "Marca dispositivo enganche", type: "text", section: "acoplamiento", clause: "44.1" },
  { name: "installableCouplingDevices", label: "Dispositivos acoplamiento que puede instalar", type: "text", section: "acoplamiento", clause: "45" },
  { name: "valueDc", label: "Valor Dc", type: "float", section: "acoplamiento", clause: "45.1" },
  { name: "valueV", label: "Valor V", type: "float", section: "acoplamiento", clause: "45.1" },
  { name: "valueD", label: "Valor D", type: "float", section: "acoplamiento", clause: "45.1" },
  { name: "valueS", label: "Valor S", type: "float", section: "acoplamiento", clause: "45.1" },
  { name: "stationaryNoiseLevel", label: "Nivel sonoro parado", type: "float", section: "medioambiental", clause: "46" },
  { name: "stationaryNoiseLevelRpm", label: "RPM Nivel sonoro parado", type: "float", section: "medioambiental", clause: "46" },
  { name: "drivingNoiseLevel", label: "Nivel en marcha", type: "float", section: "medioambiental", clause: "46" },
  { name: "emissionsLevel", label: "Nivel emisiones", type: "text", section: "medioambiental", clause: "47" },
  { name: "specificCo2Emissions", label: "Emisiones especificas CO2", type: "float", section: "medioambiental", clause: "49.5" },
  { name: "remarks", label: "Observaciones", type: "text", section: "varios", clause: "52" },
  { name: "vehicleEquippedWith", label: "Vehiculo equipado con", type: "text", section: "varios", clause: "54" },
  { name: "gearCount", label: "Número de marchas", type: "text", section: "ficha_reducida", clause: "FR" },
  { name: "frontSuspension", label: "Suspension delantera", type: "text", section: "ficha_reducida", clause: "FR" },
  { name: "rearSuspension", label: "Suspension trasera", type: "text", section: "ficha_reducida", clause: "FR" },
  { name: "steeringMethod", label: "Metodo direccion", type: "text", section: "ficha_reducida", clause: "FR" },
  { name: "serviceBraking", label: "Frenado servicio", type: "text", section: "ficha_reducida", clause: "FR" },
  { name: "secondaryBraking", label: "Frenado socorro", type: "text", section: "ficha_reducida", clause: "FR" },
  { name: "parkingBraking", label: "Frenado estacionamiento", type: "text", section: "ficha_reducida", clause: "FR" },
  { name: "abs", label: "ABS", type: "text", section: "ficha_reducida", clause: "FR" },
  { name: "indirectVision", label: "Vision indirecta", type: "text", section: "ficha_reducida", clause: "FR" },
  { name: "doorCountAndArrangement", label: "Número y disposición de puertas", type: "text", section: "ficha_reducida", clause: "FR" },
  { name: "frontProtection", label: "Prot delantera", type: "text", section: "ficha_reducida", clause: "FR" },
  { name: "cabDeflector", label: "Deflector cabina", type: "text", section: "ficha_reducida", clause: "FR" },
  { name: "typeApprovalOptions", label: "Opciones homologacion tipo", type: "text", section: "ficha_reducida", clause: "FR" },
];
