// Generado a partir de BackEnd/bbdd.xml — metadatos de UI del formulario de Masas y Dimensiones.
export type MassesFieldType = "text" | "float";

export const MASSES_FIELDS: { name: string; label: string; type: MassesFieldType }[] = [
  { name: "firstAxleToBodyDistance", label: "De 1eje a caja", type: "float" },
  { name: "frontOverhang", label: "Voladizo delantero", type: "float" },
  { name: "maxVehicleWidth", label: "Ancho maximo vehículo", type: "float" },
  { name: "maxHeightFromGround", label: "Altura maxima desde el suelo", type: "float" },
  { name: "reeferUnitCentreOfGravity", label: "Cdg maq frio", type: "float" },
  { name: "reeferUnitMass", label: "Masa maq frio", type: "float" },
  { name: "liftPlatformCentreOfGravity", label: "Cdg plataforma elevadora", type: "float" },
  { name: "liftPlatformMass", label: "Masa plataforma elevadora", type: "float" },
  { name: "hookCentreOfGravity", label: "Cdg gancho", type: "float" },
  { name: "couplingPointMass", label: "Masa punto acoplamiento", type: "float" },
  { name: "seatsCentreOfGravity", label: "Cdg plazas", type: "float" },
  { name: "seatsMass", label: "Masa plazas", type: "float" },
  { name: "seats2Mass", label: "Masa plazas 2", type: "float" },
  { name: "seats2CentreOfGravity", label: "Cdg plazas2", type: "float" },
  { name: "fuelCentreOfGravity", label: "Cdg combustible", type: "float" },
  { name: "fuelCapacity", label: "Capacidad combustible", type: "float" },
  { name: "chassisCabTareAxle1", label: "Tara 1eje chasis cabina", type: "float" },
  { name: "chassisCabTareAxle2", label: "Tara 2eje chasis cabina", type: "float" },
  { name: "tareAxle1", label: "Tara 1 eje", type: "float" },
  { name: "tareAxle2", label: "Tara 2 eje", type: "float" },
  { name: "tareAxle3", label: "Tara 3 eje", type: "float" },
  { name: "centreAxleTrailerMass", label: "Masa remolque ejes centrales", type: "float" },
  { name: "semiTrailerTotalLength", label: "Largo total O4", type: "float" },
  { name: "semiTrailerBodyLength", label: "Largo carrozado O4", type: "float" },
  { name: "semiTrailerTare", label: "TARA O4", type: "float" },
  { name: "theoreticalBodyTare", label: "Tara teorica carrozado", type: "float" },
  { name: "chassisWeighbridgeTareAxle1", label: "Tara chasiseje1 bascula", type: "float" },
  { name: "chassisWeighbridgeTareAxle2", label: "Tara chasis eje2 bascula", type: "float" },
  { name: "legacyUnusedNote", label: "Total MMTA eje2 con gancho menos el valor", type: "text" },
  { name: "craneCentreOfGravity", label: "Cdg GRUA", type: "float" },
  { name: "craneMass", label: "Masa grua", type: "float" },
  { name: "copRemarks", label: "Observaciones para RCOP", type: "text" },
  { name: "craneBoxCentreOfGravity", label: "Cdg cajon grua", type: "float" },
  { name: "boxMass", label: "Masa cajon", type: "float" },
  { name: "semiTrailer3AxleVd", label: "O4semi 3VD", type: "float" },
  { name: "semiTrailer3AxleVdAccessory", label: "O4semi3 VD accesorio", type: "float" },
  { name: "semiTrailer3AxleMaxPermissibleVd", label: "O4semi3 VD maximo Admisible", type: "float" },
  { name: "semiTrailer3AxleVp", label: "O4semi 3VP", type: "float" },
  { name: "semiTrailer3AxleLt", label: "O4semi 3LT", type: "float" },
  { name: "semiTrailer3AxleLc", label: "O4semi 3LC", type: "float" },
  { name: "semiTrailer3AxleBodyWeight", label: "O4semi 3 peso carrozado", type: "float" },
  { name: "semiTrailer3AxleTareWithBody", label: "O4semi 3 tara con carrozado", type: "float" },
  { name: "semiTrailer3AxleChassisCgHeight", label: "O4semi3 altura cdg chasis", type: "float" },
  { name: "semiTrailer3AxleCompletedCgHeight", label: "O4semi3 altura cdg completado", type: "float" },
  { name: "semiTrailer3AxleMinCompletedCgHeight", label: "O4semi3 altura minima cdg completado", type: "float" },
  { name: "semiTrailer3AxleCoveredFloorArea", label: "O4semi3 superficie suelo cubierta", type: "float" },
  { name: "semiTrailer3AxleMmaCouplingPoint", label: "O4semi3 MMApuntoacoplamiento", type: "float" },
  { name: "semiTrailer3AxleMmaCouplingPointRequested", label: "O4semi3 MMApuntoacoplamiento solicitado", type: "float" },
];
