-- CreateTable
CREATE TABLE "bodyworks" (
    "id" TEXT NOT NULL,
    "dossierId" TEXT NOT NULL,
    "bodyType" TEXT,
    "floorType" TEXT,
    "floorThickness" DOUBLE PRECISION,
    "floorWeightPerM2" DOUBLE PRECISION,
    "sideColor" TEXT,
    "roofMaterial" TEXT,
    "roofMaterialWeightPerM2" DOUBLE PRECISION,
    "sideMaterial" TEXT,
    "sideMaterialWeightPerM2" DOUBLE PRECISION,
    "sideStructureMaterial" INTEGER,
    "sideStructureTubeWeightPerMeter" DOUBLE PRECISION,
    "skirtSheet" TEXT,
    "skirtWeightPerM2" DOUBLE PRECISION,
    "subchassisProfile" TEXT,
    "subchassisMaterialWeightPerMeter" DOUBLE PRECISION,
    "windDeflector" TEXT,
    "windDeflectorHeight" DOUBLE PRECISION,
    "liftPlatformType" TEXT,
    "liftPlatformCapacity" DOUBLE PRECISION,
    "liftPlatformVoltage" DOUBLE PRECISION,
    "liftPlatformBrand" TEXT,
    "exteriorLength" DOUBLE PRECISION,
    "interiorLength" DOUBLE PRECISION,
    "exteriorWidth" DOUBLE PRECISION,
    "interiorWidth" DOUBLE PRECISION,
    "interiorHeight" DOUBLE PRECISION,
    "sidePitch" DOUBLE PRECISION,
    "roofStructureMaterial" INTEGER,
    "roofStructureMaterialWeightPerMeter" DOUBLE PRECISION,
    "trimMaterial" TEXT,
    "trimWeightPerMeter" DOUBLE PRECISION,
    "tieDownMaterial" TEXT,
    "tieDownCount" INTEGER,
    "tieDownWeightPerMeter" DOUBLE PRECISION,
    "baseMaterial" TEXT,
    "baseMaterialWeightPerMeter" DOUBLE PRECISION,
    "doorLined" BOOLEAN,
    "doorLatchCount" INTEGER,
    "hingesPerDoor" INTEGER,
    "hardwareMaterial" TEXT,
    "doorType" TEXT,
    "doorFiberWeightPerM2" DOUBLE PRECISION,
    "windDeflectorWeight" DOUBLE PRECISION,
    "liftPlatformWeight" DOUBLE PRECISION,
    "liftPlatformFitted" TEXT,
    "otherAccessories" TEXT,
    "otherAccessoriesWeight" DOUBLE PRECISION,
    "toolBox" TEXT,
    "extinguisherBox" TEXT,
    "toolBoxWeight" DOUBLE PRECISION,
    "extinguisherBoxWeight" DOUBLE PRECISION,
    "doorLatchUnitWeight" DOUBLE PRECISION,
    "hingeUnitWeight" DOUBLE PRECISION,
    "couplingDevice" TEXT,
    "couplingDeviceBrand" TEXT,
    "rearProtectionBrand" TEXT,
    "rearProtection" TEXT,
    "rearProtectionModel" TEXT,
    "rearProtectionApprovalNumber" TEXT,
    "couplingDeviceSerialNumber" TEXT,
    "otherElectricalEquipment" TEXT,
    "leafSpringReinforcement" TEXT,
    "leafSpringReinforcementWeight" DOUBLE PRECISION,
    "interiorLight" TEXT,
    "toolBoxSize" TEXT,

    CONSTRAINT "bodyworks_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "bodyworks_dossierId_key" ON "bodyworks"("dossierId");

-- AddForeignKey
ALTER TABLE "bodyworks" ADD CONSTRAINT "bodyworks_dossierId_fkey" FOREIGN KEY ("dossierId") REFERENCES "dossiers"("id") ON DELETE CASCADE ON UPDATE CASCADE;
